server:
  port: 8090
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  redis:
    url: localhost
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.geek01.yupaoBackend.constant
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com:
      geek01:
        yupaoBackend:
          controller: info
          service: info
          mapper: debug
knife4j:
  enable: ${knife4j.enable}
  openapi:
    title: "伙伴匹配系统接口文档"
    description: "伙伴匹配系统接口文档"
    email: "2878844162@qq.com"
    concat: 01geek
    url: "https://github.com/yeahwangz/Partner-Matching-System-backend"
    version: v1.0
    license: Apache 2.0
    license-url: "https://stackoverflow.com/"
    terms-of-service-url: "https://stackoverflow.com/"
    group:
      group1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.geek01.yupaoBackend.controller
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false